#!/usr/bin/env python

"""

                  888
                  888
                  888
88888b.   .d88b.  88888b.   .d88b.  888  888
888 "88b d88""88b 888 "88b d88""88b `Y8bd8P'
888  888 888  888 888  888 888  888   X88K
888  888 Y88..88P 888 d88P Y88..88P .d8""8b.     http://nobox.io
888  888  "Y88P"  88888P"   "Y88P"  888  888     http://github.com/noboxio

Author: Brian McGinnis
Date: 6/23/17
"""

import json
from watson_developer_cloud import ConversationV1


class Conversation:
    """Conversation class that connects to the watson conversation service"""

    def __init__(self, usr, pas, workspace):
        """Create conversation object.

        usr -- username for watson conversation service
        pas -- password for watson conversation service
        workspace -- workspace ID for the workspace in the conversation service.
        """
        self.convo = ConversationV1(
            username=usr,
            password=pas,
            version='2017-05-26')
        self.workspace_id = workspace

    def sendMessage(self, message):
        """Send a message to the conversation service.

        Sends a message to the conversation service and then return the
        response generated by the conversation service.

        message -- message to send to conversation service.
        """
        response = self.convo.message(
            workspace_id=self.workspace_id,
            message_input={'text': message})
        jsn = json.loads(json.dumps(response))
        print(jsn)
        return jsn['output']['text'][0]

# con = conversation('154b5b29-d1ca-4ff2-be09-c33c5e1d9e20' , 'pmNftYlpvMS8','9ef80568-2a3b-4790-a8e0-363c0bc7d237')
# respon = con.sendMessage("LOVE ME JERRY")
# print(respon)
